app/models.py
import re
from app import db
from datetime import datetime
from random import randint

from flask_security import UserMixin, RoleMixin


post_tags = db.Table('post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
 )

pattern = r'[^\w+]'


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(300))
    slug = db.Column(db.String(300), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug =  re.sub(pattern, '-', self.title).lower()[:50] + str(randint(1000, 9999))

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'

    def __str__(self):
        return self.title



class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    slug = db.Column(db.String(150))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.name:
            self.slug =  re.sub(pattern, '-', self.name).lower()[:50] + str(randint(1000, 9999))

    def __repr__(self):
        return f'<Tag id: {self.id}, name: {self.name}>'

    def __str__(self):
        return self.name

# To connect tags manually:
# t1 = Tag.query.first()
# p1 = Post.query.first()
# p1.tags.append(t)


# For flask security

roles_users = db.Table('roles_users',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
    )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(110), unique=True)
    password = db.Column(db.String(600))
    name = db.Column(db.String(100))
    active = db.Column(db.Boolean())

    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

    def __repr__(self):
        return f'<User id: {self.id}, name: {self.name}>'

    def __str__(self):
        return self.name

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(200))

    def __repr__(self):
        return f'<Role id: {self.id}, name: {self.name}>'

    def __str__(self):
        return self.name

app/posts/forms.py
from wtforms import StringField, TextAreaField
from wtforms.validators import InputRequired, Length
from flask_wtf import FlaskForm


class PostForm(FlaskForm):
    title = StringField('Title', validators=[InputRequired('Enter the title'), Length(min=4, max=300, message='Title must be 4-300 characters')])  
    body = TextAreaField('Body', validators=[InputRequired('Enter the body'), Length(min=50, max=10000, message='Body must contain at least 50 characters')]) 

app/app.py
from flask import Flask, redirect, url_for, request

from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security, current_user

from config import Configuration


app = Flask(__name__)
app.config.from_object(Configuration)


db = SQLAlchemy(app)


# For DB migration:
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


# For admin page:
from models import Post, Tag, User, Role

class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('Admin')
    
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class BaseModelView(ModelView):
    # if something is changed in post -> new slug must be generated
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)
    

class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']


class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']


admin = Admin(app, 'FlaskBlog', url='/blog', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))


# For security:

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

# Endow user `admin` role:
# user = user_datastore.add_user(name='Madi', ...)
# role = user_datastore.add_role(name='Admin', ...)
# db.session.commit()
# user_datastore.add_role_to_user(user, role)
# db.session.commit()

app/main.py
from app import app, db
from posts.blueprint import posts
from views import *
from fill_db import fill_posts


if __name__ == '__main__':
    # fill_posts()
    app.register_blueprint(posts, url_prefix='/blog')
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import request
from flask import redirect
from flask import url_for
from flask import render_template

from flask_security import login_required

from models import Post, Tag
from app import db

from .forms import PostForm



posts = Blueprint('posts', __name__, template_folder='templates')
# the name 'posts' will be used in url_for function 
# For instance, posts.index or posts.post_detail



# Must be above than `index` because it will cosnider `create` as `q` parameter
# http://localhost:5000/blog/create
@posts.route('/create', methods=['POST','GET'])
@login_required
def create_post():
    form = PostForm(meta={'csrf': False})

    if request.method == 'POST':
        print('Got:', form)
        if form.validate_on_submit():
            print('Validated')
            title = request.form.get('title')
            body = request.form.get('body')

            try:
                post = Post(title=title, body=body)
                db.session.add(post)
                db.session.commit()
            except Exception as e:
                print('Error:', e)           

            return redirect(url_for('posts.index'))
        else:
            print('Form did not pass validation')

    return render_template('posts/create_post.html', form=form)



@posts.route('/')
def index():
    page = request.args.get('page')
    q = request.args.get('q','')

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', pages=pages, q=q)


# http://localhost:5000/blog/first-post
@posts.route('/<slug>')
def post_detail(slug):
    # post not POST request but blog text
    post = Post.query.filter(Post.slug==slug).first_or_404()

    return render_template('posts/post_detail.html', post=post, tags=tags)


# slug for specific 'tags' -> e.g., http://localhost:5000/blog/tag/sports
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts 

    return render_template('posts/tag_detail.html',tag=tag, posts=posts)




@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', form=form, post=post)

app/views.py
from app import app
from flask import redirect
from flask import url_for
from flask import render_template


@app.route('/')
def home():
    return redirect(url_for('posts.index'))


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html', error=e), 404

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    Create your own post!
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class="control-label") }}
                    {{ field(class="form-control") }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Sumbit</button>
        </form>
    </div>
{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class="control-label") }}
                    {{ field(class="form-control") }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Edit</button>
        </form>
    </div>
{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index title
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% set q='&q=%s' % q %}
{% block content %}
    {% for post in pages.items %}

    {% if post.slug %}
        <p><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
            {{ post.title }}
        </a></p>
    {% endif %}
    {% endfor %}

    <nav aria-label="...">
        <ul class="pagination">
          <li {% if pages.has_prev %} class="page-item active" {% else %} class="page-item disabled" {% endif %}>
            <a class="page-link" href="./?page={{ pages.prev_num }}{{ q }}" tabindex="-1" aria-disabled="true"><<</a>
          </li>
          
          {% for page in pages.iter_pages() %}

            <li {% if page == pages.page %} class="page-link active" {% else %} class="page-link" {% endif %}>
                <a class="page-link" href="./?page={{ page }}{{ q }}">{% if page %} {{ page }} {% else %} ... {% endif %}</a>
            </li>
                
          {% endfor %}
          
          <li {% if pages.has_next %} class="page-item active" {% else %} class="page-item disabled" {% endif %}>
            <a class="page-link" href="./?page={{ pages.next_num }}{{ q }}">>></a>
          </li>

        </ul>
    </nav>

{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
    <div class="tags">
        {% for tag in tags %}
            {% if tag.slug %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="badge bg-dark">{{ tag.name }}</span>
            </a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

{% block content %}
    {{ post.body }}
    <hr align="center" width="500" size="2" color="#000000" />
    <p>Published: {{ post.created }}</p>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}":
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
            {{ post.title }}
            </a>
        </div>
    {% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %} | Flask Application
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://masseffect.neoseeker.com/wiki/Volus#:~:text=The%20Volus%20are%20a%20Citadel,which%20explains%20their%20small%20stature.&text=Due%20to%20the%20physical%20appearance,adept%20for%20war%20and%20combat.">Volus</a>
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              
              <li class="active">
                <a href=" {{ url_for('posts.index') }} ">Blog<span class="sr-only">(current)</span></a>
              </li>
              
              <li>
                <a href="/login">Login</a>
              </li>
              
            </ul>

            <form class="navbar-form navbar-left" method="GET">
              <div class="form-group">

                <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.args.get('q','') }}">

              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
              {% if current_user.has_role('Admin') %}
              <!-- <li><a href="{{ url_for('posts.create_post') }}">+ Post</a></li> -->
              <li><a href="/admin">Admin</a></li>
              <li><a href="create">+ Post</a></li>
              {% endif %}
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

    <div class="container">  
    <div class="row">
        <h1>
            {% block content_title %}

            {% endblock %}
        </h1>

        {% block content %}
        
        {% endblock %}

    </div>
    </div>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block title %}
    Home page
{% endblock %}


{% block content_title %}
    Home page
{% endblock %}


{% block content %}
    Content
{% endblock %}

app/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>{{ _('Menu') }}</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Register') }}</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password') }}</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">{{ _('Confirm account') }}</a></li>
  {% endif %}
</ul>
{% endif %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{% extends 'base.html' %}
{% block title %}
  Login page
{% endblock %}

{% block content_title %}
<div class="col-md-offset-3 col-md-6">
  {{ _('Login') }}
</div>
{% endblock %}


{% block content %}

<div class="col-md-offset-3 col-md-6">
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
    {{ login_user_form.hidden_tag() }}
    {{ render_field_with_errors(login_user_form.email, class='form-control') }}
    {{ render_field_with_errors(login_user_form.password, class='form-control') }}
    {{ render_field_with_errors(login_user_form.remember) }}
    {{ render_field(login_user_form.next) }}
    {{ render_field(login_user_form.submit, class='btn btn-success') }}
  </form>
  {% include "security/_menu.html" %}
</div>

{% endblock %}